application: charles-blog
version: live
runtime: python
api_version: 1

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 )$


handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: deferred.py
  login: admin

- url: /admin/.*
  script: admin.py
  login: admin

- url: /static/images/fileicons/.*
  script: zip_handler.py

- url: /static/js/plugins
  static_dir: staticfck/js/plugins
  
- url: /static/([^/]+)/(.*)
  static_files: themes/\1/static/\2
  upload: themes/[^/]+/static/.*
    
- url: /fckeditor/.*
  script: zip_handler.py
  
- url: /staticfck
  static_dir: staticfck

- url: /.*
  script: static.py
